[colors]
transparent_background_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
# family = "IosevkaTerm Nerd Font"
# family = "EnvyCodeR Nerd Font"
# family = "FiraCode Nerd Font"
# style = "Retina"
# family = "Monaspace Radon"
family = "Monaspace Krypton"
style = "Regular"
