[pyprland]
plugins = [
    "scratchpads",
    "magnify",
    "layout_center",
]

[scratchpads.pavucontrol]
animation = "fromTop"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "50% 30%"
unfocus = "hide"

[scratchpads.bpytop]
animation = "fromBottom"
command = "alacritty --class scratchpad -e bpytop"
class = "scratchpad"
lazy = true
size = "60% 60%"

[scratchpads.rofi]
command = "rofi -show drun"
lazy = true
animation = "fromBottom"
class = "rofi"

[scratchpads.irssi]
command = "alacritty --class scratchpad -e irssi"
class = "scratchpad"
animation = "fromRight"
size = "46% 86%"

[scratchpads.term]
command = "alacritty --class scratchpad"
animation = "fromTop"
class = "scratchpad"
size = "50% 50%"
lazy = true

[layout_center]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
margin = 70
