[pyprland]
plugins = [
    "scratchpads",
    "magnify",
    "layout_center",
]

[scratchpads.btop]
animation = "fromBottom"
command = "alacritty --class scratchpad -e btop"
class = "scratchpad"
lazy = true
size = "60% 60%"

[scratchpads.irssi]
command = "alacritty --class scratchpad -e irssi"
class = "scratchpad"
animation = "fromRight"
size = "46% 86%"

[scratchpads.term]
command = "alacritty --class scratchpad"
animation = "fromTop"
class = "scratchpad"
size = "50% 50%"
lazy = true

[layout_center]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
margin = 70
