-- vim.api.nvim_create_autocmd("FileType", {
--     callback = function(args)
--         local ft = vim.bo[args.buf].filetype
--
--         -- optionally skip some filetypes
--         if ft == "" then
--             return
--         end
--
--         pcall(vim.treesitter.start, args.buf, ft)
--     end,
-- })
